#!/bin/bash

usage() {
    echo "Options:
    -f | --font     <font>      Sets the font
    -h | --help                 Prints this help message"
    exit $1
}

unset dmenu_args
while [[ $# > 0 ]]; do
    opt="$1"
    shift

    case $opt in
        -f|--font)
            [[ $# > 0 ]] || usage 1
            dmenu_args=( -fn "$1" "${dmenu_args[@]}" )
            shift
            ;;
        -h|--help)
            usage 0
            ;;
        *)
            usage 1
            ;;
    esac
done

# Date format, for use as the prompt.
date=$(date +"%a %d. %b %R")

# dmenu cannot display more than 30 lines, to avoid screen clutter. Only relevant if you have more than 30 windows open.
height=$(wmctrl -l | wc -l)
if [[ $height -gt 30 ]]
	then heightfit=30
	else heightfit=$height
fi

dmenu_args=( -b -i -p "$date" -l "$heightfit" "${dmenu_args[@]}" )

num=$(wmctrl -l | sed 's/  / /' | cut -d " " -f 4- | nl -w 3 -n rn | sed -r 's/^([ 0-9]+)[ \t]*(.*)$/\1 - \2/' | dmenu "${dmenu_args[@]}" | cut -d '-' -f -1)
[[ -z "$num" ]] && exit
wmctrl -l | sed -n "$num p" | cut -c -10 | xargs wmctrl -i -a
