#!/bin/bash

# Date format, for use as the prompt.
date=$(date +"%a %d. %b %R")

# dmenu cannot display more than 30 lines, to avoid screen clutter. Only relevant if you have more than 30 windows open.
height=$(wmctrl -l | wc -l)
if [[ $height -gt 30 ]]
	then heightfit=30
	else heightfit=$height
fi

wmctrl -l | sed 's/  / /' | cut -d " " -f 4- | nl -n ln | sed 's/     / - /' | cut -c 1-4,6- | dmenu -b -i -p "$date" -l $heightfit | cut -c 5- | xargs wmctrl -a
